mongodburl = "mongodb://admin:password123@localhost:27017/"
database = "nekobox"
products_collection = "neko_products"
scrapping_collection = "neko_scrappings"
scrapping_item_collection = "neko_scrappings_item"